spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                  allowedOrigins: "http://localhost:3000"
                  allowedHeaders: "*"
                  allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
          default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
          - id: auth_route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/auth/**
          - id: permission_route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/permissions/**
          - id: user_route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/user/**
